### ISSUE TITLE
from where I get g2.ini file

### ISSUE THREAD

**Issue by Ashish3013** [Senzing/risk-score-calculator#28]
java -jar target/risk-scoring-calculator-0.0.1-SNAPSHOT.jar -iniFile /opt/senzing/g2/resources/templates/G2Module.ini -mqQueue risk -mqHost puffin-01.rmq2.cloudamqp.com -mqUser jfwxcszc -jdbcConnection amqps://jfwxcszc:h0XKiPM1p2spXghV5d0ROECJoRlILFdQ@puffin.rmq2.cloudamqp.com/jfwxcszc~
WARNING: trusted sources is not configured!
WARNING: query risk criteria is not configured!
Exception in thread "main" java.lang.UnsatisfiedLinkError: no G2 in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at com.senzing.g2.engine.G2JNI.<clinit>(G2JNI.java:16)
	at com.senzing.listener.senzing.service.g2.G2Service.init(G2Service.java:47)
	at com.senzing.calculator.scoring.risk.service.g2.G2ServiceExt.init(G2ServiceExt.java:27)
	at com.senzing.calculator.scoring.risk.service.RiskScoringService.init(RiskScoringService.java:147)
	at com.senzing.calculator.scoring.risk.RiskScoringCalculator.run(RiskScoringCalculator.java:25)
	at com.senzing.calculator.scoring.risk.RiskScoringCalculatorApp.main(RiskScoringCalculatorApp.java:39)

**Comment by oskar700** [comment]
It looks like JNI is not finding libG2.so.  Make sure your LD_LIBRARY_PATH is set.
I noticed you are pointing to a template version of the ini file.  You should use the one located in the senzing project.
If you haven't set up a project yet you can find the directions here:
https://docs.senzing.com/quickstart/#creating-a-senzing-project

**Comment by oskar700** [comment]
Ashish3013 - Is this issue solved?  If not let me know if there is more to do.  If I don't hear back within 7 days I presume this is not a problem anymore and will close this ticket.

**Comment by oskar700** [comment]
Closing since no activity for 3 months.
