### ISSUE TITLE
unit test failing

### ISSUE THREAD

**Issue by oskar700** [Senzing/risk-score-calculator#77]
**Describe the bug**
The build process reports failed unit tests:
`[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.senzing.calculator.scoring.risk.service.RiskScorerTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.112 s - in com.senzing.calculator.scoring.risk.service.RiskScorerTest
[INFO] Running com.senzing.calculator.scoring.risk.service.RiskScoringServiceTest
[ERROR] Tests run: 20, Failures: 0, Errors: 20, Skipped: 0, Time elapsed: 0.354 s <<< FAILURE! - in com.senzing.calculator.scoring.risk.service.RiskScoringServiceTest
[ERROR] processHavingGreenDataQuality(com.senzing.calculator.scoring.risk.service.RiskScoringServiceTest)  Time elapsed: 0.021 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at com.senzing.calculator.scoring.risk.service.RiskScoringServiceTest.setupTest(RiskScoringServiceTest.java:61)
Caused by: java.lang.IllegalStateException: JMockit didn't get initialized; please check the -javaagent JVM initialization parameter was used
	at com.senzing.calculator.scoring.risk.service.RiskScoringServiceTest.setupTest(RiskScoringServiceTest.java:61)
`

**To Reproduce**
Pull down code and run 
mvn clean install
The above error will occur.

**Expected behavior**
The build should pass without any reported errors.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
No other data.

**Comment by oskar700** [comment]
Fixed with #78
